### ISSUE TITLE
理财之道

### ISSUE THREAD

**Issue by chunpu** [chunpu/blog#79]
工作一年多, 感觉理财真的很重要, 1000元有1000元的理法, 100万有100万的理法

理财总的来说就一点, 风险和收益成反比

我认为的理财阶梯如下

- 余额宝: 4.0 ~ 5.0
- 招财宝
- 国债: 5.0 ~ 5.5
- 普通理财产品: 3.0 ~ 8.0
- 信托:  7.0 ~ 12.0
- 股票基金 0 ~ 100
- 股票 0 ~ 300
- 风投 0 ~ 10000

理财说白了就是钱生钱, 懂理财和不懂理财的人在10年后差距是巨大的, 非常可惜的是余额宝拉小了这种差距, 但这不意味着理财就可以忽视

一个已经有 100w 的人如果理财非常牛逼, 年收益达到 20%, 那就和一个年收入 20w 的人差不多了, 试想一下, 已经有 1000w 的人会有多厉害

理财结构
---

20% 是非常理想的收益, 显然里面必然有大于信托的理财, 一般来说就是股票

我自己比较推荐的理财结构是一半**低风险理财**, 一半**高风险理财**

#### 低风险理财

所谓低风险就是股票上面的理财, 余额宝, 国债之类的, 如果总资金在 100w 以上, 根据上面的结构, 低风险投资有 50w 多. 建议办一张银行的日均 50w 的高端卡, 比如招行的金葵花, 一般银行都会提供高门槛较高收益的低风险理财, 比如 5.5 左右的 20w 起步的理财, 这样的好处是比较灵活, 因为有时候银行会给高端用户提供 7.0% 以上的高端理财, 类信托

如果总资金低于 100w, 则低风险投资少于 50w, 建议直接买国债, 或者买招财宝, 这样至少保证了利率接近 5%, 建议买国债的原因是国债同样需要抢购的, 并且虽然买 3年, 也是可以一年就拿到一年的利息, 还算灵活而且可以锻炼理财思维

对于不怕风险的投资人来说, 企业债券更是他们的选择, 企业发行的借贷利率通常大于信托, 可以到 10% ~ 20%.它的风险就是企业倒闭

#### 高风险理财

高风险理财对大部分人来说就是股票和股票基金, 如果你工作实在太忙, 又不像错过牛市这波浪潮, 强烈建议你买股票基金, 所谓股票基金就是有个操盘手帮你炒股, 你只需要交手续费就行, 一般股票基金稍弱于指数基金, 牛的时候也会跟着涨, 熊的时候也不至于跌这么快

当然如果你工作不算忙, 那还是建议直接炒股, 股票持有是一件让人非常愉快的事情, 买自己喜欢或者看好的企业的股票, 这多开心啊

我理想的工作就是每天上一会网, 然后喝着咖啡看研报, 看新闻, 然后选择自己想操作的股票

#### 更高的理财

难道我们就止步于股票吗?

不是的, 之所以强调 1000 块也有1000 块的理法, 是因为要不断强化自己对理财的敏感度, 怎样能用钱赚钱?

1. 借钱给别人, 拿利息 (低风险理财)
2. 低买高卖 (高风险理财)

除了股票, 我们生活中依然能看到不少暴利的东西, 你有没有想过要去分一杯羹呢,代购其实也是理财的一种, 从外国走私再卖给朋友. 同样的, 看到农民种的果子只卖几块一斤, 自己在市场上买却要几十一斤, 你为什么不能去买卖水果呢

在高风险理财中, 有两个能力特别重要

- 估值判断
- 预见性

比如之前的乐视, 眼睁睁的看着它的股价从 60 多跌到 30, 如果你相信它的估值就该有优酷的三倍, 那就应该果断抄底

预见性也同样重要, 大的可以是10年前预测房价要上涨, 小的可以是在一个月前预见情人节会让交友网站火一下

掌握理财, 根本不会发生坐吃山空的情况, 我经常看到几年前的彩票得主把奖金挥霍完, 现在过得还不如从前之类的新闻. 简单思考一下这种事为什么经常发生? 究其原因, 买彩票本就是最弱的投机方式, 买的人通常经济条件差, 也没走过理财阶梯, 拿到这么一大笔钱,只想着该怎么用, 自然撑不了几年

商人拿到第一桶金就可以不断捞金, 懒汉就算中了 500万几年后也会花光, 其根本差异就是对财富的管理理念吧

总而言之, 理财不再是单纯的钱生钱技巧, 而是一种生活方式, 一种可持续发展的理念, 相信自己判断, 敢于去猜未来, 生活一定会更加美好

**Comment by yutingzhao1991** [comment]
理想的工作就是每天上一会网，然后看着自己的股票涨涨涨 😄

**Comment by Evllis** [comment]
楼主还有更详细的知识吗。。。求指导，我想学习理财，但是对这方面一窍不通。又怕掉坑，好怕。
