### ISSUE TITLE
租房 VS 买房

### ISSUE THREAD

**Issue by chunpu** [chunpu/blog#85]
周末研究了一下在帝都租房和买房的区别, 纯属意淫, 并没有实际经验
# 一些基础设定

北京夫妻二人
- 每人工资 1.5w, 加起来 3w, 税后实得 2w
- 有 90w 存款(包括公积金)
- 每月公积金收入 3 \* 0.24 = 0.72w (北京每月交工资的24%的公积金)
- 北京租售比 = 1 : 555
- 想买300w的房
- 每月房租 300 / 555 = 0.54w
- 每月其他支出 5000 元
- 储蓄理财年化收益按 6% 算
# 买房

要买的房价 = 300w

选择 30% 首付 = 300 \* 30% = 90w

还需要公积金贷款 = 300 - 90 = 210w

每月开销 = 5000

每月公积金还款总金额不能超过工资一半, 夫妻二人的工资加起来为3w一个月, 每月还款上限为1.5w

根据公积金还款计算器(使用等额本金, 容易计算, 虽然利息多一点)算20年期, 每月需还14437元, 正好不到 1.5w

每月剩余资金 = 税后收入 + 公积金 - 放贷 - 生活支出 = 2 + 3 \* 0.24 - 1.44 - 0.5 = 0.78w

工资定投储蓄理财所得 = 0.78 \* 12 \* 20 \* Math.pow(1.06, 10) = 335w
## 20年后资产

实际资产 = 300w房子一套 + 335万存款 = 300 + 335 = 635w

优势是已经住了20年自己的家
## 风险
- 20年后房子贬值
- 周边发展不好
- 邻居不好
- 换工作, 换城市
- 换工作断档, 公积金接不上
# 租房

每月剩余资金 = 税后收入 - 房租 - 其他支出 = 2 - 0.54 - 0.5 = 0.96w 减去房租和消费

20年后资产
- 公积金 = 0.72 \* 12 \* 20 = 172.8w
- 工资定投储蓄理财 = 0.96 \* 12 \* 20 \* Math.pow(1.06, 10) = 412.6w
- 90w 资金理财 = 90 \* Math.pow(1.06, 20) = 288.6w

最后资产 = 172.8 + 412.6 + 288.6 = 874w

没算中介费之类的
## 风险
- 不买房小孩无法正常上小学, 不过300w住的房也不会是好的学区房, 还有私立的选择
- 房子大幅增值, 房租上升
- 经常换房要中介费
- 理财收益大幅降低
- 租房各种不爽
# 总结

20年后资产对比 874 - 635 = 239w

租房的比买房的多出了 239w, 缺点是一直过着租房的生活
## 估算和实际不同的地方
- 工资会变动
- 工作会有奖金
- 房价会变
- 租房的话公积金可以提前取
# Q & A

Q: 理财收益年化 6% 是怎么来的

A: 不考虑 P2P 等风险较高的理财, 使用保本保息的招财宝一年, 利息约 6.0 ~ 6.5 之间, 其实可以做到更高, 详见[理财选择一年6.5%的还是两年7%的好](https://github.com/chunpu/blog/issues/84)

Q: 租售比是什么?

A: 租售比 = 月租金 / 房价, 比如 300w 的房租每月租金 5400 元, 租售比 = 0.54 / 300 = 1 : 555

Q: 为什么租售比定为 1 : 555?

A: 知乎上说的, 来自 http://www.zhihu.com/question/20799544/answer/44545583, 一居室可能没这么高, 也就是说一居室可能房租更贵

Q: 为什么租房会比买房多这么钱?

A: 这是目前租售比过高导致的, 所以租房看起来比买房稍微实惠点

Q: 既然如此那我就一直租房好了

A: 政策上优惠削弱了租售比的劣势, 买房并不会亏大多, 而且买房相当于强制定投, 对于没有理财概念的人, 绝对是优势. 90% 的人都没有正确的理财观念, 很多人生活"潇洒", 想买啥就买啥, 根本存不下钱, 还喜欢瞎xx炒股买基金, 亏得一塌糊涂, 工资1w, 最后能存下3k的人都很少. 因此, 生活"潇洒"的人应该及早买房, 不然40岁多了还是没啥钱

Q: 为什么认为房价不会大幅上涨?

A: 互联网高度发达, 如果大众熟知的产品中有被严重被低估的东西, 那大家就会蜂拥而上, 比如房子, 股票

Q: 为什么工资定投储蓄理财是 `Math.pow(1.06, 10)`?

A: 因为定投收益等于初始一下子存入的一半, 所以20年定投 = 10年直接存入

Q: 你会选哪种?

A: 我不需要贷款

**Comment by yutingzhao1991** [comment]
**我不需要贷款**

这句话亮了！~

===

第一句基础设定就过不了 ： 北京**夫妻二人**。每人工资 1.5w, 加起来 3w, 税后实得 2w

**Comment by chunpu** [comment]
是说首先要有一个妹子?

**Comment by yutingzhao1991** [comment]
有空研究怎么理财 不如研究如何找个女朋友 :D

**Comment by hjin-me** [comment]
买房了？

**Comment by webLiang** [comment]
大佬最后买了么
